[package]
name = "muvera-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { version = "0.16.1", features = ["rayon"] }
num-traits = "0.2.19"
rand = "0.9.1"
rand_distr = "0.5.1"
rayon = "1.10.0"
